#ifndef CORE_STATIC_VARIABLE_DEFINATIONS_H
#define CORE_STATIC_VARIABLE_DEFINATIONS_H
namespace statics_definations { namespace core {
static int ERROR_LOGIN_LOGIN_AND_PASSWORD_NOT_BE_EMPITY = -1;
static int LOGIN_WINDOW_POSITION  = 2;
static int PROJECT_LIST_WINDOW  = 3;
static int PROJECT_EDIT_WINDOW = 4;
}}
#endif // CORE_STATIC_VARIABLE_DEFINATIONS_H
